from _typeshed import Incomplete
from beancount.utils import defdict as defdict, file_type as file_type

HEAD_DETECT_MAX_BYTES: Incomplete

class _FileMemo:
    name: Incomplete
    def __init__(self, filename) -> None: ...
    def convert(self, converter_func): ...
    def mimetype(self): ...
    def head(self, num_bytes: int = ..., encoding: Incomplete | None = ...): ...
    def contents(self): ...

def mimetype(filename): ...
def head(num_bytes: int = ..., encoding: Incomplete | None = ...): ...
def contents(filename): ...
def get_file(filename): ...
