import unittest
from _typeshed import Incomplete
from beancount import loader as loader
from beancount.ingest import extract as extract, importer as importer, scripts_utils as scripts_utils
from beancount.parser import parser as parser
from beancount.utils import misc_utils as misc_utils, test_utils as test_utils

extract_main: Incomplete

class TestScriptExtractFromFile(test_utils.TestCase):
    def test_extract_from_file__empty(self) -> None: ...
    def test_extract_from_file__ensure_sorted(self): ...
    def test_extract_from_file__ensure_sanity(self) -> None: ...
    def test_extract_from_file__min_date(self) -> None: ...
    def test_extract_from_file__existing_entries(self) -> None: ...
    def test_extract_from_file__explicitly_marked_duplicates_entries(self) -> None: ...
    def test_extract_from_file__raises_exception(self) -> None: ...

class TestPrintExtractedEntries(scripts_utils.TestScriptsBase, unittest.TestCase):
    class ExtractTestImporter(importer.ImporterProtocol):
        def file_account(self, _): ...
    def test_print_extracted_entries(self, mock_extract_from_file) -> None: ...

class _LoaderImporter(importer.ImporterProtocol):
    filename: Incomplete
    account: Incomplete
    def __init__(self, filename, account) -> None: ...
    def identify(self, file): ...
    def extract(self, file, existing_entries: Incomplete | None = ...): ...
    def file_account(self, _): ...

class TestScriptExtract(test_utils.TestTempdirMixin, unittest.TestCase):
    config_filename: Incomplete
    downloads: Incomplete
    dl_checking: Incomplete
    dl_credit: Incomplete
    def setUp(self) -> None: ...
    def test_extract(self) -> None: ...
    def test_extract_find_dups_once_only_with_many_files(self, mock) -> None: ...
    def test_extract_with_previous_entries(self) -> None: ...
    def test_extract_no_files(self) -> None: ...
    def test_extract_examples(self) -> None: ...
