from _typeshed import Incomplete
from beancount.core import account as account
from beancount.ingest import cache as cache, identify as identify
from beancount.utils import misc_utils as misc_utils

def file_one_file(filename, importers, destination, idify: bool = ..., logfile: Incomplete | None = ...): ...
def file(importer_config, files_or_directories, destination, dry_run: bool = ..., mkdirs: bool = ..., overwrite: bool = ..., idify: bool = ..., logfile: Incomplete | None = ...): ...
def move_xdev_file(src_filename, dst_filename, mkdirs: bool = ...) -> None: ...

DESCRIPTION: str

def add_arguments(parser) -> None: ...
def run(args, parser, importers_list, files_or_directories, hooks: Incomplete | None = ...): ...
