from _typeshed import Incomplete
from beancount.core import flags as flags

class ImporterProtocol:
    FLAG: Incomplete
    def name(self): ...
    def identify(self, file) -> None: ...
    def extract(self, file, existing_entries: Incomplete | None = ...) -> None: ...
    def file_account(self, file) -> None: ...
    def file_name(self, file) -> None: ...
    def file_date(self, file) -> None: ...
