from _typeshed import Incomplete
from beancount.ingest import cache as cache, extract as extract
from beancount.parser import printer as printer
from collections.abc import Generator

def pytest_addoption(parser) -> None: ...
def with_importer(importer): ...
def with_testdir(directory): ...
def find_input_files(directory) -> Generator[Incomplete, None, None]: ...
def compare_contents_or_generate(actual_string, expect_fn, generate) -> None: ...

class ImporterTestBase:
    def test_identify(self, importer, file) -> None: ...
    def test_extract(self, importer, file, pytestconfig) -> None: ...
    def test_file_date(self, importer, file, pytestconfig) -> None: ...
    def test_file_name(self, importer, file, pytestconfig) -> None: ...
    def test_file_account(self, importer, file, pytestconfig) -> None: ...
