import unittest
from _typeshed import Incomplete
from beancount.ingest import cache as cache, extract as extract
from beancount.ingest.importer import ImporterProtocol as ImporterProtocol
from beancount.parser import printer as printer
from beancount.utils import test_utils as test_utils
from beancount.utils.misc_utils import deprecated as deprecated
from collections.abc import Generator

class ToolNotInstalled(OSError): ...

class ImportFileTestCase(unittest.TestCase):
    maxDiff: Incomplete
    importer: Incomplete
    def __init__(self, importer) -> None: ...
    def test_expect_identify(self, filename, msg) -> None: ...
    def test_expect_extract(self, filename, msg) -> None: ...
    def test_expect_file_date(self, filename, msg) -> None: ...
    def test_expect_file_name(self, filename, msg) -> None: ...

def find_input_files(directory) -> Generator[Incomplete, None, None]: ...
def compare_sample_files(importer, directory: Incomplete | None = ..., ignore_cls: Incomplete | None = ...) -> Generator[Incomplete, None, None]: ...
