from _typeshed import Incomplete
from beancount.ingest import extract as extract, scripts_utils as scripts_utils
from beancount.utils import test_utils as test_utils

extract_main: Incomplete

def run(args, parser, importers_list, files_or_directories) -> None: ...

class TestParseArguments(scripts_utils.TestScriptsBase):
    def test_test_scripts_base(self) -> None: ...
    def test_parse_arguments__insufficient(self) -> None: ...
    def test_parse_arguments__invalid(self) -> None: ...
    def test_parse_arguments__sufficient(self) -> None: ...
    def test_parse_arguments__multiple(self) -> None: ...

INGEST_MAIN_WITH_DUPS: str

class TestImplicitInvocationMethods(scripts_utils.TestScriptsBase):
    FILES: Incomplete
    def test_implicit_invocation(self) -> None: ...
    def test_implicit_invocation_with_ingest_call(self) -> None: ...
