import unittest
from _typeshed import Incomplete
from beancount.ingest import cache as cache, extract as extract, file as file, identify as identify, importer as importer
from beancount.parser import version as version
from beancount.utils import test_utils as test_utils

DESCRIPTION: str

def identify_main(): ...
def extract_main(): ...
def file_main(): ...
def ingest(importers_list, detect_duplicates_func: Incomplete | None = ..., hooks: Incomplete | None = ...): ...
def create_legacy_arguments_parser(description: str, run_func: callable): ...
def trampoline_to_ingest(module): ...
def run_import_script_and_ingest(parser, argv: Incomplete | None = ..., importers_attr_name: str = ...): ...

class _TestFileImporter(importer.ImporterProtocol):
    account: Incomplete
    regexp_mime: Incomplete
    regexp_contents: Incomplete
    def __init__(self, name, account, regexp_mime, regexp_contents) -> None: ...
    def name(self): ...
    def identify(self, file): ...
    def file_account(self, _): ...

IMPORT_FILE: str
INGEST_MAIN: str
OFX_FILE: str
CSV_FILE: str
TXT_FILE: str

class TestScriptsBase(test_utils.TestTempdirMixin, unittest.TestCase):
    FILES: Incomplete
    def setUp(self) -> None: ...
