from _typeshed import Incomplete
from beancount.core import account as account
from beancount.ingest import importer as importer

class FilingMixin(importer.ImporterProtocol):
    filing_account: Incomplete
    prefix: Incomplete
    def __init__(self, **kwds) -> None: ...
    def name(self): ...
    def file_account(self, file): ...
    def file_name(self, file): ...
