from __future__ import annotations

from collections import defaultdict
from typing import Any, Optional

class Distribution:
    hist: defaultdict[Any, int]
    def __init__(self: Distribution) -> None: ...
    def empty(self: Distribution) -> bool: ...
    def update(self, value: Any) -> None: ...
    def min(self: Distribution) -> Optional[Any]: ...
    def max(self: Distribution) -> Optional[Any]: ...
    def mode(self: Distribution) -> Optional[Any]: ...
